// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD54TIGnZ9k3LDyDa-f1SRXtDXKygpboPE',
    appId: '1:956925056695:web:743e7508fff3030c879f32',
    messagingSenderId: '956925056695',
    projectId: 'project-flutter-pbb',
    authDomain: 'project-flutter-pbb.firebaseapp.com',
    storageBucket: 'project-flutter-pbb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo0B8xJdJZbTcJQS9CmHzlV7BKm5jKeHc',
    appId: '1:956925056695:android:a1b8536ab408330d879f32',
    messagingSenderId: '956925056695',
    projectId: 'project-flutter-pbb',
    storageBucket: 'project-flutter-pbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACo6-Dx3u6cpexLNHwhKKo3VbTgc9-GdM',
    appId: '1:956925056695:ios:b80eba0b6248bf9d879f32',
    messagingSenderId: '956925056695',
    projectId: 'project-flutter-pbb',
    storageBucket: 'project-flutter-pbb.appspot.com',
    iosBundleId: 'com.example.firebaseapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACo6-Dx3u6cpexLNHwhKKo3VbTgc9-GdM',
    appId: '1:956925056695:ios:b80eba0b6248bf9d879f32',
    messagingSenderId: '956925056695',
    projectId: 'project-flutter-pbb',
    storageBucket: 'project-flutter-pbb.appspot.com',
    iosBundleId: 'com.example.firebaseapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD54TIGnZ9k3LDyDa-f1SRXtDXKygpboPE',
    appId: '1:956925056695:web:bf575423728ca15a879f32',
    messagingSenderId: '956925056695',
    projectId: 'project-flutter-pbb',
    authDomain: 'project-flutter-pbb.firebaseapp.com',
    storageBucket: 'project-flutter-pbb.appspot.com',
  );

}