// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAIyTIUC0TJCoL5DVtRbniDRUFORt0HOY',
    appId: '1:471047292995:web:fc8b37deda0657aebbacf6',
    messagingSenderId: '471047292995',
    projectId: 'prakflutterfirebase-9bccc',
    authDomain: 'prakflutterfirebase-9bccc.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-9bccc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQB2rxoIiNQREH8d9bEHk_Z2fG9rP8Zz8',
    appId: '1:471047292995:android:b56581774bdb8858bbacf6',
    messagingSenderId: '471047292995',
    projectId: 'prakflutterfirebase-9bccc',
    storageBucket: 'prakflutterfirebase-9bccc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ3PbSlvqiOAMlTyzcy_TE9axhwKjzND0',
    appId: '1:471047292995:ios:3d81f83d74964634bbacf6',
    messagingSenderId: '471047292995',
    projectId: 'prakflutterfirebase-9bccc',
    storageBucket: 'prakflutterfirebase-9bccc.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ3PbSlvqiOAMlTyzcy_TE9axhwKjzND0',
    appId: '1:471047292995:ios:3d81f83d74964634bbacf6',
    messagingSenderId: '471047292995',
    projectId: 'prakflutterfirebase-9bccc',
    storageBucket: 'prakflutterfirebase-9bccc.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAIyTIUC0TJCoL5DVtRbniDRUFORt0HOY',
    appId: '1:471047292995:web:de7ef915a6dd52a0bbacf6',
    messagingSenderId: '471047292995',
    projectId: 'prakflutterfirebase-9bccc',
    authDomain: 'prakflutterfirebase-9bccc.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-9bccc.appspot.com',
  );
}
